# Generated by Django 3.1.dev20200118190725 on 2020-04-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название компании')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL производителя')),
                ('img', models.ImageField(help_text='500x500px', upload_to='manufacturer', verbose_name='Логотип компании')),
                ('country', models.CharField(max_length=60, verbose_name='Страна производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
    ]
