# Generated by Django 3.1.dev20200410100027 on 2020-05-22 07:10

from django.db import migrations, models
import manufacture.models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='img',
            field=models.ImageField(help_text='500x500px', upload_to=manufacture.models.manufacture_img_name, verbose_name='Логотип компании'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название компании'),
        ),
    ]
