# Generated by Django 3.1.dev20200410100027 on 2020-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200423_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер квартиры'),
        ),
    ]
