# Generated by Django 3.1.dev20200410100027 on 2020-04-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200424_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users', verbose_name='Фото профиля'),
        ),
    ]
