# Generated by Django 3.1.dev20200410100027 on 2020-05-22 07:10

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200425_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, upload_to=account.models.profile_img_name, verbose_name='Фото профиля'),
        ),
    ]
