# Generated by Django 3.1.dev20200410100027 on 2020-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200522_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grid',
            field=models.BooleanField(default=True, verbose_name='Сетка товаров'),
        ),
    ]
