# Generated by Django 3.1.dev20200410100027 on 2020-06-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.BooleanField(default=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grid',
            field=models.BooleanField(default=False, verbose_name='Сетка товаров'),
        ),
    ]
