# Generated by Django 3.1.dev20200410100027 on 2020-06-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200606_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='', max_length=50, verbose_name='Автор комментария'),
            preserve_default=False,
        ),
    ]
