# Generated by Django 3.1.dev20200410100027 on 2020-06-05 21:52

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Улица')),
                ('number_house', models.CharField(blank=True, max_length=50, verbose_name='Номер дома')),
                ('number_room', models.CharField(blank=True, max_length=50, verbose_name='Номер квартиры')),
                ('photo', models.FileField(blank=True, upload_to=account.models.profile_img_name, verbose_name='Фото профиля')),
                ('grid', models.BooleanField(default=False, verbose_name='Сетка товаров')),
                ('theme', models.BooleanField(default=True, verbose_name='Тема')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
