# Generated by Django 3.1.dev20200410100027 on 2020-06-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20200611_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.order', verbose_name='Заказ'),
        ),
    ]
