# Generated by Django 3.1.dev20200410100027 on 2020-06-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(max_length=200, verbose_name='Пользователь'),
        ),
    ]
