# Generated by Django 3.1.dev20200410100027 on 2020-06-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200612_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=200, verbose_name='Почта пользователя'),
            preserve_default=False,
        ),
    ]
