# Generated by Django 3.1.dev20200118190725 on 2020-04-03 12:19

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Понятный url')),
                ('img', models.ImageField(upload_to=catalog.models.category_img_name, verbose_name='Картинка категории')),
            ],
        ),
    ]
