# Generated by Django 3.1.dev20200118190725 on 2020-02-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя товара')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL товара')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добовления')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Categories')),
            ],
        ),
    ]
