# Generated by Django 3.1.dev20191227090824 on 2020-02-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsimage',
            options={'verbose_name': 'Картинка товара', 'verbose_name_plural': 'Картинки товаров'},
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='categorys', verbose_name='Кaртинка категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='понятный url'),
        ),
    ]
