# Generated by Django 3.1.dev20200410100027 on 2020-06-08 16:33

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to=catalog.models.category_img_name, verbose_name='Картинка категории '),
        ),
    ]
