# Generated by Django 3.1.dev20191227090824 on 2020-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(max_length=200, verbose_name='Текст комментария'),
        ),
    ]
