# Generated by Django 3.1.dev20200118190725 on 2020-02-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200211_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
