# Generated by Django 3.1.dev20200118190725 on 2020-02-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodimg', to='catalog.Product'),
        ),
    ]
