# Generated by Django 3.1.dev20200118190725 on 2020-02-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200212_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsimage',
            name='products',
        ),
        migrations.AddField(
            model_name='productsimage',
            name='prodimg',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product'),
            preserve_default=False,
        ),
    ]
