# Generated by Django 3.1.dev20200118190725 on 2020-02-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200212_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsimage',
            name='prodimg',
        ),
        migrations.AddField(
            model_name='productsimage',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prodimg', to='catalog.Product'),
            preserve_default=False,
        ),
    ]
