# Generated by Django 3.1.dev20200118190725 on 2020-02-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200214_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Страна производитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(default=1, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(default=1, help_text='месяцев', verbose_name='Гарантия'),
            preserve_default=False,
        ),
    ]
