# Generated by Django 3.1.dev20200118190725 on 2020-02-22 12:34

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200214_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='categorys/%__import__(name)/img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=builtins.id, max_length=30, unique=True, verbose_name='URL товара'),
        ),
    ]
