# Generated by Django 3.1.dev20200118190725 on 2020-02-22 14:39

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200222_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to=catalog.models.category_img_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True, verbose_name='URL товара'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='img',
            field=models.ImageField(upload_to=catalog.models.product_img_name),
        ),
    ]
