# Generated by Django 3.1.dev20191227090824 on 2020-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200223_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, verbose_name='Код компании')),
                ('name', models.CharField(max_length=15, verbose_name='Название компании')),
                ('img', models.ImageField(help_text='500x500px', upload_to='manufacturer', verbose_name='Логотип компании')),
                ('country', models.CharField(max_length=60, verbose_name='Страна производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productsimage',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
