# Generated by Django 3.1.dev20191227090824 on 2020-02-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200223_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacture',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='catalog.Manufacture', verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
