# Generated by Django 3.1.dev20191227090824 on 2020-02-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_manufacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
    ]
