# Generated by Django 3.1.dev20191227090824 on 2020-02-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='code',
        ),
    ]
