# Generated by Django 3.1.dev20191227090824 on 2020-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_manufacture_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='action',
            field=models.BooleanField(default=0, verbose_name='Акционный товар?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='complect',
            field=models.TextField(default='нет', verbose_name='Комплект поставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(default='', help_text='700x200px', upload_to='poster', verbose_name='Акционный постер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.IntegerField(default=1, help_text='шт.', verbose_name='Количество товара'),
            preserve_default=False,
        ),
    ]
