# Generated by Django 3.1.dev20191227090824 on 2020-02-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200223_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='action',
        ),
        migrations.RemoveField(
            model_name='product',
            name='poster',
        ),
    ]
