# Generated by Django 3.1.dev20191227090824 on 2020-02-24 21:09

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200223_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsimage',
            name='products',
        ),
        migrations.AddField(
            model_name='productsimage',
            name='alt',
            field=models.CharField(default='', max_length=50, verbose_name='Алт. Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsimage',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prodimg', to='catalog.Product', verbose_name='Продукт'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='categorys', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(help_text=' руб.', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Заполняется автоматически', max_length=30, unique=True, verbose_name='URL товара'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='img',
            field=models.ImageField(upload_to=catalog.models.product_img_name, verbose_name='Картинка(и)'),
        ),
    ]
