# Generated by Django 3.1.dev20200410100027 on 2020-06-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200609_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='set',
        ),
    ]
