# Generated by Django 3.1.dev20191227090824 on 2020-04-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price_per_item',
            field=models.IntegerField(default=1, verbose_name='Цена за одну штуку'),
        ),
    ]
