# Generated by Django 3.1.dev20191227090824 on 2020-04-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200411_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Актиность товара в корзине'),
        ),
    ]
