# Generated by Django 3.1.dev20200118190725 on 2020-04-07 10:32

from django.db import migrations, models
import django.db.models.deletion
import poster.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='poster',
            field=models.ImageField(help_text='700x200px', upload_to=poster.models.poster_img_name, verbose_name='Изоброжение товара постере'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodposter', to='products.Product'),
        ),
    ]
