# Generated by Django 3.1.dev20200118190725 on 2020-04-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('poster', '0002_auto_20200407_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prodposter', to='products.Product'),
        ),
    ]
