# Generated by Django 3.1.dev20200118190725 on 2020-04-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_auto_20200407_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='poster',
            new_name='posterimg',
        ),
    ]
