# Generated by Django 3.1.dev20200118190725 on 2020-04-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_auto_20200407_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='posterimg',
            new_name='img',
        ),
    ]
