# Generated by Django 3.1.dev20200410100027 on 2020-06-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_productsinorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinorder',
            name='user',
        ),
    ]
