# Generated by Django 3.1.dev20200410100027 on 2020-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsinbasket',
            old_name='session_key',
            new_name='username_basket',
        ),
        migrations.AlterField(
            model_name='productsinbasket',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='productsinorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Состояние'),
        ),
    ]
