# Generated by Django 3.1.dev20200410100027 on 2020-04-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_auto_20200423_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsinbasket',
            name='username',
        ),
        migrations.AddField(
            model_name='productsinbasket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basket.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='productsinbasket',
            name='session_key',
            field=models.CharField(default=123123123213123, max_length=128),
            preserve_default=False,
        ),
    ]
