# Generated by Django 3.1.dev20200410100027 on 2020-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20200423_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsinbasket',
            name='user',
            field=models.CharField(default=111, max_length=128),
            preserve_default=False,
        ),
    ]
